CLIENT_ID = "ESP32-CO2-PARTICLE"
DHCP_NAME = "ESP32-CO2-PARTICLE"
TOPIC_ERRORS = 'virheet/koti/esp32'
NTPSERVER = 'pool.ntp.org'
CO2_SENSOR_TX_PIN = 17
CO2_SENSOR_RX_PIN = 16
CO2_SENSOR_UART = 1
# https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html
TFT_SPI = 2  # VSPI = ID2
TFT_DC_PIN = 2
TFT_CS_PIN = 5
TFT_MOSI_PIN = 23
TFT_CLK_PIN = 18  # = SCK
TFT_RST_PIN = 4
TFT_MISO_PIN = 19
TOUCHSCREEN_SPI = 1  # HSPI = ID1
TFT_TOUCH_SCLK_PIN = 14
TFT_TOUCH_MOSI_PIN = 13  # T_DIN
TFT_TOUCH_MISO_PIN = 12  # T_DO
TFT_TOUCH_CS_PIN = 15
TFT_TOUCH_IRQ_PIN = 35
